### ISSUE TITLE
docker-compose yamls not running on Windows 7

### ISSUE THREAD

**Issue by kletkeman** [IBM-Blockchain/fabric-images#19]
kletkeman@tp-letkemank  /c/blockchain/src/github.com/IBM-Blockchain/fabric-images/docker-compose (master)
$ docker-compose -f single-peer-ca.yaml up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 65, in main
  File "compose\cli\main.py", line 117, in perform_command
  File "compose\cli\main.py", line 849, in up
  File "compose\project.py", line 372, in up
  File "compose\project.py", line 539, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 33, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\client.py", line 139, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1057, in request
  File "httplib.py", line 1097, in _send_request
  File "httplib.py", line 1053, in endheaders
  File "httplib.py", line 897, in _send_output
  File "httplib.py", line 859, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 49, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
docker-compose returned -1

**Comment by kletkeman** [comment]
BTW -- runs fine on MacOS

**Comment by masterDev1985** [comment]
I am able to run these docker-compose files on my Windows 7 system.  My recommendation would be to uninstall Docker Toolbox, remove any trace of Docker, Python, and Oracle VirtualBox from your machine, and then reinstall Docker Toolbox.  I suspect something is wrong with the Python installation on your machine.  It's a shot in the dark, but nothing in this error message is a strong indicator to me that our compose files are causing the issues.

**Comment by kletkeman** [comment]
Ok, Thanks. I'll try that when I get a chance. I am currently working on the Mac, where it is going well.

**Comment by jdstuart** [comment]
I have the same issue.  Docker Tools on Windows 7

**Comment by nmors** [comment]
i am getting the same issue on win 10

**Comment by mastersingh24** [comment]
@jdstuart  @nmors  Looks like you are not even getting things up and running with docker-compose on Windows?  (as an aside I recommend Docker for Windows whne using Win10).

One thing you need to make sure that you do is run all commands from the "Docker Quickstart Terminal"

**Comment by radhna** [comment]
getting the folowing error while running yaml file from within Docker Toolbox on Win 7-
Radhna@ADMINIB-0AQ5PNL MINGW64 ~/blockchain/fabric-images/docker-compose (master)
$ docker-compose -f single-peer-ca.yaml up -d
Pulling membersrvc (ibmblockchain/fabric-membersrvc:x86_64-0.6.1-preview)...
←[31mERROR←[0m: Get https://registry-1.docker.io/v2/ibmblockchain/fabric-membersrvc/manifests/x86_64-0.6.1-preview: unauthorized: incorrect username or password

Can anyone help ?

**Comment by nmors** [comment]
@mastersingh24 thanks. I was using git bash before, I figured that it now works fine when using the Docker Quickstart Terminal. I switched from Docker for windows using Hyper-V to Docker toolbox with VirtualBox.. Works fine now with toolbox, realising that this was the problem..

**Comment by Eddikos** [comment]
@mastersingh24 Thanks a lot, I was using normal CMD and was surprised I it wouldn't work. Stupid me
